jfairbank/redux-saga-test-plan

src/index.js
src/types.js
test/testSaga.test.js

Rather than backing up a hardcoded number of steps which can be brittle if your saga changes, this PR lets you create named "marks" using the `mark` function. You can pass this name to `back` to return to that point.

Add named marks that you can back up to

---

__tests__/expectSaga/expectSaga.test.js
src/expectSaga.js

Hey man, awesome project! Did run into some issues when I was trying to do some more complex integration tests with expectSaga. Turns out the stopDirty behaviour was the cause of this. I hope I understood correctly what that was supposed to do, because removing it didn't break any tests.
Listed my changes below. Please let me know if anything is not OK. Thanks!
Fixed and added tests for:
- expectSaga ignored the silenceTimeout flag when any kind of fork was involved.
- forks caused the exportSaga timeout period to be extended. Whenever a fork was added expectSaga would reset the timeout. Adding a fork once would result in timeout period times 2. Keep adding forks and expectSaga would never time out.
Added test (to make sure nothing broke with this change):
- expectSaga waiting for all …

Fix saga promise handling

---

.travis.yml

According to [this](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), Travis CI supports yarn out of the box if `yarn.lock` is present, without needing to manually install it.
Also, since Node 7 is the latest version, it seemed appropriate to add it to the list of CI builds.

Test on Node 7 and take advantage of TravisCI's yarn support

---

docs/unit-testing/saga-helpers.md

A small typo, but spent a couple minutes wondering why my copy paste from the docs wouldn't work so figured it was worth the fix.

Fixed typo in saga-helpers doc

---

__tests__/expectSaga/expectSaga.test.js
src/expectSaga/index.js

This is related to #123 
Also the included test case will actually timeout and fail in the current implementation. Because although the MainTask.done will resolve, expectSaga will keep waiting for the Promise returned by endPoint to resolve, however it won't because it's rejected. 
```
function endpoint() {
return Promise.reject();
}
```
May I have your feedback on this ^_^

expectSaga does not wait for Promises to resolve

---

README.md

There is some really great documentation on the external Gitbook site but it's not at all obvious it exists when glancing at the readme. The external links are tucked away at the bottom of the page under a small 'Getting Started' section. This new layout is based on how redux and redux-saga has organized their documentation links.

Emphasize external documentation in readme

---

__tests__/expectSaga/reducer/sequential.test.js
src/expectSaga/index.js

During saga test the actions dispatched from within a saga are not executed instantly which results in a wrong execution order for the tests.
We encountered this in a saga where a selector is performed right after a dispatched action, using the `withReducer` option. The store was not yet updated when the selector was executed, meaning the saga failed based on incorrect data.
This is a simple solution that only delays the store execution when a delayTime is given.

Omit the Promise.resolve to execute reducer in same tick

---

index.d.ts

`ExpectApi.silentRun()` should return `Promise<RunResult>`, just like `ExpectApi.run()`.

[typings] Fix ExpectApi Typescript typings

---

effects.d.ts

Allow to use selectors with many arguments. Current version of selector types do not support selectors with many arguments.
Selector like `(state, arg1) => any ` shows type error.

Update selector type definition

---

__tests__/expectSaga/assertions/throws.test.js
docs/SUMMARY.md
docs/integration-testing/thrown-errors.md
index.d.ts
src/expectSaga/expectations.js
src/expectSaga/index.js
src/expectSaga/sagaWrapper.js

Adds the `throws` method on `expectSaga` which allows for testing of error pathways in sagas. Closes #125 and #147. Fully documented and tested.
Examples:
```js
function* saga() {
yield put({ type: 'API_STARTED' });
try {
yield call(callApi, '/users/', 'get');
} catch (e) {
yield put({ type: 'API_FAILED' });
throw e;
}
yield put({ type: 'API_SUCCESS' });
}
it('cleans up on API error', () =>
expectSaga(saga)
.provide([
[matchers.call.fn(callApi), throwError(apiError)],
])
.put({ type: 'API_STARTED' })
.call.fn(callApi)
.put({ type: 'API_FAILED' })
.throws(apiError)
.run());
```
Failure Example:
```js
function* saga() {
throw new Error();
}
it('throws an error of type CustomError', () => {
return expectSaga(saga)
.throws(CustomError)
.run();
});
```
```
Expected to throw error of type: …
```

Add error assertion to expectSaga

---

src/utils/async.js

Issue was caused by window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ that override some window fn
Make sur the needed functions are available now
Links of the issue [here](https://github.com/jfairbank/redux-saga-test-plan/issues/255)

Fix issue #255

---

index.d.ts

When used with typescript, I saw that `testSaga` and `expectSaga` functions were not typesafe with their parameters.
Just used the power of typescript generics to fix that :)

fix: typesafe testSaga & expectSaga

---

__tests__/expectSaga/assertions/throws.test.js
src/expectSaga/sagaWrapper.js

This wraps the `throw` call on the generator to catch any errors that might get thrown in a catch block. Now `expectSaga` can assert on errors thrown in the saga's catch blocks.
Fixes #296

Fix asserting a throw in a catch block

---

docs/integration-testing/dispatching.md

Missing method `take` to integration testing doc

fix: add missing method take to integration testing

---

effects.d.ts

Use `TakeableChannel` and `FlushableChannel` instead of `Channel` in effect typings. 
Example that this fixes
```typescript
export function* mySaga() {
const chan = yield call(makeChannel);
try {
while (true) {
const act = yield take(chan);
yield put(act);
}
} finally {
if (yield cancelled()) {
chan.close();
}
}
}
const makeChannel = () => eventChannel(emit => {
emit({ type: 'Hello' })
return () => { };
});
const channel = makeChannel();
const saga = testSaga(mySaga)
.next().call(makeChannel)
// Error happens here
// Property 'put' is missing in type 'EventChannel<unknown>' but required in type 'Channel<unknown>'
.next(channel).take(channel)
```

Fix the typing of effects that take Channels

---

docs/integration-testing/exposed-effects.md

It's just a small fix in code sample related to the wrong name of the passed argument. In the code above, we see `userSaga` function.

Fix a mistake in the documentation

---

effects.d.ts

Fixes: https://github.com/jfairbank/redux-saga-test-plan/issues/252

TypeScript: Add puttable action variant for PutEffectApi

---

index.d.ts

This pull request updates the withReducer type. This needed to provide compatibility with reducers that use more complex action. Such as reducers created with createReducer function from https://github.com/piotrwitek/typesafe-actions
At the moment withReducer allows only AnyAction type.

Add action's type to withReducer definition

---

index.d.ts

Based on [time travel API docs](http://redux-saga-test-plan.jeremyfairbank.com/unit-testing/time-travel.html), `restart` can accept an array of any. So, I fix `restart` type.

Update restart type

---

docs/integration-testing/mocking/dynamic-providers.md

I was unsure without looking at the implementation how an 'effect' was passed into a dynamic provider, although I suspected it was just the payload. This text makes it more explicit, and suggests how to investigate the structure of the payload for any given redux-saga effect.

Add clarity regarding payload

---

README.md
package.json
src/expectSaga/expectations.js
src/shared/serializeEffect.js
yarn.lock

This PR adds support for custom inspect options (depth levels & etc)
Related issues: #95 #339
Example of usage:
```js
import util from 'util';
import testSaga from 'redux-saga-test-plan';
import { put } from 'redux-saga/effects';
const largeAction = {
type: 'large-action',
payload: {
firstLevel: {
secondLevel: {
... // more levels here
},
},
},
};
function* testableSaga() {
yield put(largeAction)
}
describe('Some sagas to test', () => {
// this will allow to see the full effect objects while Expected & Actual result comparison in the console 
util.inspect.defaultOptions.depth = null;
it('testableSaga', () => {
testSaga(testableSaga)
.next()
.put({
type: 'large-action',
payload: { ... },
})
.next()
.isDone();
});
});
```

Add support for custom inspect options (depth levels & etc)

---

package.json

Yarn PnP requires a packageExtension due to the missing peer dependencies.

fix: add missing peer dependencies

---

index.d.ts

This makes a small tweak to how the parameters for a saga given to `expectSaga` or `testSaga` are inferred.
This snippet does not work with the latest version, 4.0.4 and TypeScript 4.6
```ts
function* helperSaga<T>(foo: T, saga: (item: T) => any) {
yield saga(channel);
}
function* handler(num: number) {
yield num;
}
expectSaga(helperSaga, 42, handler);
```
The TypeScript compiler has an error on the last line:
```
function handler(num: number): Generator<number, void, unknown>
Argument of type '(num: number) => Generator<number, void, unknown>' is not assignable to parameter of type '(item: unknown) => any'.
Types of parameters 'num' and 'item' are incompatible.
Type 'unknown' is not assignable to type 'number'.ts(2345)
```
By making the type for the saga's params inferred as a generic …

Fixes inferred args type of expectSaga and testSaga
